- hosts: kubernetes-master
  become: yes
  gather_facts: false
  tasks:
    - name: Get cluster join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: Set cluster join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}" 
- hosts: worker-1
  become: yes
  tasks:
    - name: Join kubernetes cluster on Micro-Box
      shell: "{{ hostvars['kubernetes-master'].join_command }} >> node_joined.txt"
      args:
        chdir: /home/usman
        creates: node_joined.txt

